// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvmayyihnjcemfilupoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2bWF5eWlobmpjZW1maWx1cG96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMzE5NDYsImV4cCI6MjA1OTgwNzk0Nn0.VUimGS6HuAd6ebD7qQEV0iQBckICxqSBM5Jh_i4WW-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);